export const GET_ADS="GET_ADS";
export const GET_PROFILE="GET_PROFILE";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const FETCHING_FAVOURITES_ADS = "FETCHING_FAVOURITES_ADS";
export const CHANGE_CAR_STATUS_MYADS = "CHANGE_CAR_STATUS_MYADS";
export const CHANGE_CAR_STATUS_FAVOURITESADS = "CHANGE_CAR_STATUS_FAVOURITESADS";
export const FETCHING_FAVOURITES_ADS_DONE = "FETCHING_FAVOURITES_ADS_DONE";