export const SEARCH_FETCHING_ENABLED="SEARCH_FETCHING_ENABLED";
export const SEARCH_GET_ADS = "SEARCH_GET_ADS";
export const SEARCH_MAKE_PARAMS = "SEARCH_MAKE_PARAMS";
export const SEARCH_MAKE_PARAMS_DONE = "SEARCH_MAKE_PARAMS_DONE";
export const GET_SEARCH_PARAMS_RESULT = "GET_SEARCH_PARAMS_RESULT";
export const GET_SEARCH_PARAMS_RESULT_DONE = "GET_SEARCH_PARAMS_RESULT";
export const CLEAR_ADS = "CLEAR_ADS";
export const SEARCH_ADS_COMPLETED = "SEARCH_ADS_COMPLETED"